### ISSUE TITLE
Amount difference in partpay

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#100]
After upgrade to Billmate module 2.1.2 i got difference in partpayAfterAddtocartbutton.

Screen from product:
![partpay-product](https://cloud.githubusercontent.com/assets/13641326/10638015/0bcbe76a-7809-11e5-9b08-d0eae309789b.png)
Screen from checkout
![partpay-checkout](https://cloud.githubusercontent.com/assets/13641326/10638019/0f1b1490-7809-11e5-83f1-dfb9ec51a4d7.png)

**Comment by Boxedsolutions** [comment]
What is the shipping cost for this? 
@kryllem Its added to the partpayment on checkout.

**Comment by kryllem** [comment]
Default is set to 0 as pick up in store.

**Comment by Boxedsolutions** [comment]
Is it in the checkout also. The partpayment cost is calculated with the shipping cost included. Or did you choose pickup in store to get this?

**Comment by kryllem** [comment]
There is no shipping cost assigned to transaction.
Partpayment cost is different at product view, in checkout at peyment methods and partpayment options.
You are welcome to see it at (figurgrossisten)(.)(se)

**Comment by Boxedsolutions** [comment]
Should be fixed. Needs to test.

**Comment by victorauren** [comment]
Works in both 1.5 and 2.1
Clossing issue
