### ISSUE TITLE
All of our plugins should have the same structure as much as possible.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#101]
In card and bank:

Total value should be divided and changed to Minimum value and Maximum value like the other stores.

In invoice and part pay:

The options in the dropdown menu should say Yes and No. Server should be called Testmode.

**Comment by victorauren** [comment]
[SWE]
- Beskrivningen för BillmateID bör ändras till "Billmate-Id för att använda Billmates tjänster"
- Beskrivning för Secret bör ändras till "Billmatenyckel (Secret) för att använda Billmates tjänster"
- Frågetecknet-iconen för BIllmate Bank - Beskrivning kan tas bort
- En tanke är om orderstatusarna kan visas på svenska?

[ENG]
- Description for BillmateID should be changed to "To use Billmates services, you'll need a Billmate ID
-Description for Secret should be changed to "To use Billmates services, you'll need a Billmate Key"
- The questionmark-icon on BIllmate Bank-Description should be removed. 
- Is there a way to present orderstatus in swedish if swedish is the chosen language?

**Comment by Boxedsolutions** [comment]
Regarding the status translation its up to the customer to add own Localized statuses.

**Comment by victorauren** [comment]
Ok checked the descriptions and i looked good. We ignore the language on orderstatus and I close this issue.
