### ISSUE TITLE
The standard description of our payment methods vary too much. They should be formated the same.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#102]
They should be formated like this:

Plugin_name - Description text Special text Terms

e.g.

Billmate Invoice - Pay within 14-days (19.00 invoice fee) payment terms
Billmate Partpay - Pay from 107 SEK/month payment terms (In this case we have no standard description text. If they want to use it, it's put infront of "Pay from...".)
Billmate Card - Pay with VISA and Mastercard (There is no special text here)
Billmate Bank - Pay with bank transfer (There is no special text here)

The only part that should be changed when changing description text is the description part. The rest should be hard coded. Today if I change description in invoice the description text is changed but if I do it in Card the entire text is replaced.

Today they vary a lot and it looks weird. We should do the same for all of our plugins.

What do you think @andyjohansson?

**Comment by Boxedsolutions** [comment]
@andyjohansson @victorauren Whats your opinion in this?

**Comment by victorauren** [comment]
I agree that is should look the same in all platforms. But I think that you should be able to change text if you like. But the default should be plugin - description. 
Is there a possible to add the same feature as in woocommerce, (se attached image)
![woocommerce installningar ver22 wordpress](https://cloud.githubusercontent.com/assets/14887835/13249420/6fa2e220-da24-11e5-80cd-c43edebd59c4.png)

**Comment by Boxedsolutions** [comment]
Not for the moment. Woocommerce uses shortcodes. 

But its allways possible to change the translation files and move the %s to change where it outputs dynamic data.

**Comment by Boxedsolutions** [comment]
As it is now its: 
Payment Method - Default Description
of
Payment method - Custom Description

In case of invoice
Billmate Invoice - Description (xx invoice fee is applied on your order). Terms

Should we for Partpayment
Billmate Partpayment - Description (Pay from xx/month) Terms

Just so I understand how to apply it. For both oc1 and oc2 in the same place?

**Comment by victorauren** [comment]
Sound good. lets test it and see how it turns out

**Comment by victorauren** [comment]
fixed
