### ISSUE TITLE
Description in Part pay doesn't work.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#103]

**Comment by Boxedsolutions** [comment]
How can we format it? 
Should it replace pay from xx / month?

**Comment by victorauren** [comment]
I suggest a popup-box if you click/hover over a "?" or a "i"

**Comment by Boxedsolutions** [comment]
Check if its visible

**Comment by victorauren** [comment]
It works fine, it is visivble in both 1.5 and 2.1
closing issue
