### ISSUE TITLE
Some errors in partpayment

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#104]
I got some few errors here while uninstalled and installed Partpayment module again:

Undefined index: country_id in /xxx/controller/payment/billmate_partpayment.php on line 267
Undefined index: name in /xxx/controller/payment/billmate_partpayment.php on line 267
Undefined index: sv in /xxx/view/template/payment/two/billmate_partpayment.tpl on line 186
PHP Warning:  array_keys() expects parameter 1 to be array, null given in /xxx/view/template/payment/two/billmate_partpayment.tpl on line 186
PHP Warning:  Invalid argument supplied for foreach() in /xxx/view/template/payment/two/billmate_partpayment.tpl on line 190

OC 2.0.3.1 Billmate 2.1.2

I am testing new Quick Checkout Module from Dreamventions and partpayment method is not coming up at all.

**Comment by andyjohansson** [comment]
Hi @kryllem. We will check it out as soon as possible.

**Comment by Boxedsolutions** [comment]
@kryllem 

Find row 264 and change this line from Sweden to whats your name is for Sweden, maybe Sverige:
$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "country WHERE name = 'Sweden' ORDER BY name ASC");

I think it will solve the problem, but we should look for a better solution of course.

**Comment by kryllem** [comment]
@Boxedsolutions 

About country name.
This error is coming up for all other payment methods too.
A permanent solution would be good due to future updates.

I will check solution later.

**Comment by Boxedsolutions** [comment]
We will do a permanent solution, probably in the beginning of next week.

**Comment by kryllem** [comment]
Those 2 error is solved by the change but those still occur:

PHP Notice:  Undefined index: sv in /xxx/xxx/view/template/payment/two/billmate_partpayment.tpl on line 186
PHP Warning:  array_keys() expects parameter 1 to be array, null given in /xxx/xxx/view/template/payment/two/billmate_partpayment.tpl on line 186
PHP Warning:  Invalid argument supplied for foreach() in /xxx/xxx/view/template/payment/two/billmate_partpayment.tpl on line 190

**Comment by kryllem** [comment]
Those in front end at checkout

Notice: Undefined index: sv in /xxx/catalog/model/payment/billmate_partpayment.php on line 53
Warning: Invalid argument supplied for foreach() in /xxx/catalog/model/payment/billmate_partpayment.php on line 73
