### ISSUE TITLE
Name and 3D fields in billmate card

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#107]
When I'm changing Name and 3D fields to be On, they goes back to No after saving changes and going back to module settings.

No errors is coming up.
![billmate-card](https://cloud.githubusercontent.com/assets/13641326/11114902/3a45971e-8928-11e5-9af4-e5d4c8751952.png)

**Comment by Boxedsolutions** [comment]
@victorauren Could you verify this?

**Comment by victorauren** [comment]
This is a issue, But only in Opencart v 2.x
In 1.5 it's not an issue.

**Comment by Boxedsolutions** [comment]
Should work now

**Comment by victorauren** [comment]
I don't work

**Comment by andyjohansson** [comment]
This can be scrapped due to implementation changes in this. Billmate will be doing these settings from back-end when setup is done with the acquirer.
