### ISSUE TITLE
Difference between checkout sum and sum in billmate online portal - decimal

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#108]
Total amount is not always rounded as it should be.

Example: customer checkouts out and total amount is 1257 SEK (after rounded price)
When I check in Billmate Online Portal I can see that price is kind of 1256,5874 SEK
The invoice or part payment PDF-document is correct (it shows 1257 SEK) but not at portal site.

See example.
![rounded-billmate-online](https://cloud.githubusercontent.com/assets/13641326/11118460/5cd4448c-8942-11e5-957f-87c3dc8c52be.png)

**Comment by Boxedsolutions** [comment]
Think this is fixed already. Please Verify @victorauren

**Comment by victorauren** [comment]
Works fine
closing issue
