### ISSUE TITLE
Amount of products calculated wrong

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/opencart#11]
When you order something with a product variation such as:
*Product1 - blue" 2 pc.
*Product1 - green" 2 pc.

The ammounts on the Invoice is sent like:
*Product1 - blue" 4 pc.
*Product1 - green"42 pc

If this is the case, submit a new hotfix.

**Comment by Boxedsolutions** [comment]
Do the customer has any special plugins to create product variation?
What checkout does the customer use? 

I cant reproduce in Stock install 1.5.4 or 1.5.6
