### ISSUE TITLE
Wrong orderstatus when order is placed

### ISSUE THREAD

**Issue by victorauren** [Billmate/opencart#112]
When making an order wrong orderstatus is set in Opencart. In the settings there is a own created orderstatus "Billmate Bank" but in Opencart the order gets the status Pending. Callback and API shows nothing wrong, and also the logs in Opencart shows no wrong.

**Comment by Boxedsolutions** [comment]
Should work now

**Comment by victorauren** [comment]
Works perfect!!!
Closing issue
