### ISSUE TITLE
payment_method to long - max 128 characters

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#115]
Text of payment method is to long to be stored in database.
Max 128 characters allowed.

That is only when order is under missing orders (not completed).

$_['text_fee'] and $_['text_fee2']  

or it doesn't work as it should.

**Comment by andyjohansson** [comment]
Could you verify this @victorauren?

**Comment by victorauren** [comment]
Can't recreate issue. Contact customer to get more information

**Comment by kryllem** [comment]
I have changed as followed to make description shorter and it solved my problem.


> `$_['text_title']          = 'Billmate faktura';`

> `$_['text_fee']            = '%s - Betala inom 14 dagar (%s) <a target="_blank" href="https://efinance.se/billmate/?cmd=villkor"> Köpvillkor</a>';`



> `$_['text_fee2']            = '%s - Betala inom 14 dagar (%s) <a target="_blank" href="https://efinance.se/billmate/?cmd=villkor"> Köpvillkor</a>';`

**Comment by victorauren** [comment]
I confirm that this is a issue. The first image is from missing orders. 
![missingorders](https://cloud.githubusercontent.com/assets/14887835/13248998/f5a209a8-da21-11e5-824c-c4419ec26bb1.png)

The second image is from orders

![orders](https://cloud.githubusercontent.com/assets/14887835/13249054/3801cb76-da22-11e5-9d0a-87e49a7aa098.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by victorauren** [comment]
Looks good
closing issue
