### ISSUE TITLE
Freight always 25% VAT

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/opencart#12]
The module always sends the freight VAT as 25%. Should get the freight VAT from the config of the store.

**Comment by Boxedsolutions** [comment]
The store sends The configured percent to Billmate.

**Comment by andyjohansson** [comment]
Ok, bug on API Side.

**Comment by andyjohansson** [comment]
The old API always set the freight at 25% VAT. If the fright is another VAT then 25% we need to send it as a product, so use a different flag.

**Comment by Boxedsolutions** [comment]
Should be solved now,

**Comment by joakim-combain** [comment]
Seems like you are sending in wrong flag. You are sending in flag 8, which seems to be shipping excl. vat. If you want product excl. vat you should send 0 as flag.

![shipping wrong](https://cloud.githubusercontent.com/assets/10434920/6077270/55d7859e-aded-11e4-894c-874c5fa5d4fc.png)
![shipping wrong 2](https://cloud.githubusercontent.com/assets/10434920/6077289/98770456-aded-11e4-8ddd-02d31e645165.png)

**Comment by Boxedsolutions** [comment]
In what store? And what payment method?

**Comment by joakim-combain** [comment]
I noticed that it was a cashing issue... Weird... It worked in inkognito so this issue is fixed. Closing it.
