### ISSUE TITLE
Invoice fee shows in checkout even if the amount is zero

### ISSUE THREAD

**Issue by victorauren** [Billmate/opencart#124]
If I activate the Billmate Invoice fee and set the value to 0, it shows in checkout as invoice fee is 0 kr. This should be hidden if amount is zero. 

If i deactivate the Billmate invoice fee in backend, the text is not displayed.

**Comment by victorauren** [comment]
Also shows 0 kr if amount-field is left blanc

**Comment by Boxedsolutions** [comment]
Check if my fix has solved it.

**Comment by victorauren** [comment]
It works very good
Closing issue
