### ISSUE TITLE
Address popup when invoice or part payment

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#127]
Every time customers checking out with invoice or part payment are getting following pop up after they clicked on confirm order.

![address-field](https://cloud.githubusercontent.com/assets/13641326/13642479/fa5c56ea-e61c-11e5-934f-89f3880fb85d.PNG)

This pop up coming up no matter if customer write correct information (exactly the same as in pop up) or not.

It shouldn't come up when everything matches.

**Comment by kryllem** [comment]
It doesn't come up for Testperson Approved but it do for real customers.

**Comment by Boxedsolutions** [comment]
Is it some special cases or for every customer?

**Comment by kryllem** [comment]
It's for every customers.

You can take a look at API logs.
If I am right GetAddress function appears as a result of this popup.

**Comment by Boxedsolutions** [comment]
We will look at it.

**Comment by Boxedsolutions** [comment]
Cant reproduce. And GetAddress is used not only for the popup but for validating addresses. 

So its not so that the popup is visible for every log record with GetAddress
