### ISSUE TITLE
Design checkout messed up

### ISSUE THREAD

**Issue by victorauren** [Billmate/opencart#128]
Can you please check the design in checkout. Latest moduleversion looks like attached image

![checkout](https://cloud.githubusercontent.com/assets/14887835/13702603/145e45f2-e790-11e5-8c2a-3f0fea630ea7.png)

**Comment by Boxedsolutions** [comment]
Check if this still is present.

**Comment by victorauren** [comment]
In my teststores it looks good. 
Closing issue

**Comment by victorauren** [comment]
Should test in customers store

**Comment by victorauren** [comment]
Worked better in customers store, but his theme cause the last problems. 
I close this issue.
