### ISSUE TITLE
Invoicefee-error in Opencart 2.2

### ISSUE THREAD

**Issue by victorauren** [Billmate/opencart#129]
When I activate invoicefee in opencart 2.2 (release 2 march) it shows an error in "\system\engine\loader.php on line 150"

This is the complete error "Warning: Parameter 1 to ModelTotalBillmateFee::getTotal() expected to be a reference, value given in \system\engine\loader.php on line 150"

Works in previous version

**Comment by victorauren** [comment]
add this to a later release

**Comment by Boxedsolutions** [comment]
Should be fixed with release 2.2.0
