### ISSUE TITLE
Partpayment-logs stored in error logs

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#137]
After upgrade I'm receiving a million hits generated from partpayment module extension.
![error-list-partpayment](https://cloud.githubusercontent.com/assets/13641326/14402980/a3060634-fe45-11e5-8f8f-ef9d49ad8ba1.PNG)

It is nothing good, It make it hard to check another important errors.

I hope for some fast solution here.

**Comment by kryllem** [comment]
Those logs are generated after product has been viewed and when "show partpayment on product page" mod is active. Those logs are even generated when checkout is viewed with and without show partpayment mod.
If this is necessary to generate, then it should be stored in some other place.

**Comment by victorauren** [comment]
Can you send a dump on any other log regarding paymentplans? For example if there is an line in the code it refers to? I get the logs aswell, but even if I uninstall the whole module and addons I still get the logs and it also just log the cost of the product.

**Comment by Boxedsolutions** [comment]
Should be fixed, I have cleared a lot of logging points.

**Comment by Boxedsolutions** [comment]
Can you test @paul

**Comment by kalorifri** [comment]
Tested and confirmed.
