### ISSUE TITLE
Invoice fee amount shows when no products in cart

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#138]
When customer put a product to cart and goes to checkout and then remove product from checkout the amount fee is still showing in cart. It's happening after upgrade to last version.

**Comment by victorauren** [comment]
What checkout are you using? @kryllem

**Comment by kryllem** [comment]
Ajax Quick Checkout 6.3.0.1
The fee amount is displaying immediately after product has been removed but when another page is open then cart amount is back to 0 so if this is not any bug in Billmate modules then this issue can be closed.

**Comment by victorauren** [comment]
It seems to happen with that checkout only and not in the original checkout. It works to update when switching between payment methods. 
What do you think @Boxedsolutions

**Comment by Boxedsolutions** [comment]
Strange, It seems to bee a Quick Checkout setting/issue. Think the cart is not refreshed via Ajax by Quick Checkout when remove product
