### ISSUE TITLE
Undefined variable: spPart - Show Partpay from on productpage

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#139]
PHP Notice:  Undefined variable: spPart in /xxx/vqmod/vqcache/vq2-system_modification_catalog_controller_product_category.php

**Comment by andyjohansson** [comment]
Is this related to us @Boxedsolutions @victorauren?

**Comment by Boxedsolutions** [comment]
Yes it seems so. Does it tell what row it is?

**Comment by kryllem** [comment]
It is in vqmod modification file.

Here is a bit of code:
`$this->load->model('payment/billmate_partpayment');
                $this->load->language('product/product');
$this->load->language('payment/billmate_partpayment');
                if($special)
                    $this->tax->calculate($result['special'], $result['tax_class_id'], $this->config->get('config_tax'));
                $prPart = $this->tax->calculate($result['price'], $result['tax_class_id'], $this->config->get('config_tax'));
                $payfrom = $this->model_payment_billmate_partpayment->getLowestPaymentFromTotal(($special) ? $spPart : $prPart);
                if($payfrom){
                    $billmate_payfrom = sprintf($this->language->get('billmate_payfrom'),$this->currency->getSymbolLeft(),$payfrom['monthly_cost'],$this->currency->getSymbolRight());
                } else {
                    $billmate_payfrom = false;
                }`
Row 429 in modified file 
Row 104 (i think) in your .xml file

**Comment by Boxedsolutions** [comment]
Change $spPart to $special and see if the problem still occur. 

Its in ocmod file so you will make the changes there. Will look at this in the weekend.

**Comment by kryllem** [comment]
Done, will hear back if I get a new hit on it.
Thanks.
