### ISSUE TITLE
Prevent invoice and partpay when gift card and certain product in cart

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#149]
Hi there,

What I need is an ability to prevent shops with invoice and party payment when:
- virtual gift card is in cart
- specified product is in cart (ex. physical gift card)

It's to prevent fraud attempts.

We are gonna to promote shopping of gift card and would like to have those features made as soon as possible.

**Comment by kalorifri** [comment]
The available payment options in checkout are based on the store settings and payment option settings. If you want to display available payment options to customer based on the items in cart there are available plugins for that purpouse.
Try search on google or for example: http://www.opencart.com/index.php?route=extension/extension

Try search for payment options based on product category.
An example of extension is http://www.opencartx.com/restrict-payment-methods 
We have not tested it.

**Comment by kryllem** [comment]
What about virtual gift cards?
I think it should be restricted by default in your module as it is easy fraud way.
Or is it ok if customer pay with invoice for a gift card?

**Comment by Boxedsolutions** [comment]
Are you thinking about using opencarts standard voucher system or is it some thirdparty extension you have in mind?

**Comment by kryllem** [comment]
Here is a situation.
I buy a gift card with your personal number  using invoice/party payment and receive gift card to my e-mail.
I make a purchase to myself by paying with that gift card and get stuff send to my address.

Standard Built-in.

**Comment by kryllem** [comment]
You can't test it on opencart demo site but make a test in your infrastructure.

http://demo.opencart.com/index.php?route=account/voucher

**Comment by Boxedsolutions** [comment]
Where in opencart settings is the setting for allow purchase of a voucher?

**Comment by kryllem** [comment]
I think it is allow as standard, and you can not change the setting.
Check if you have amount specified in System - Settings - Option - Vouchers.
Tested in 2.0.X

**Comment by Boxedsolutions** [comment]
You can always add it yourself. 

find /catalog/model/payment/billmate_invoice.php and billmate_partpayment.php add this line under the row with public function getMethod($address, $total){:
if(!empty($this->session->data['vouchers']))
            return array();     

This will inactivate method if vouchers exist in cart.

**Comment by kryllem** [comment]
Great, will test it.
Thanks.
