### ISSUE TITLE
Billmatepopup mobile browser problem

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/opencart#15]
It doesnt show up at all.

**Comment by Boxedsolutions** [comment]
Should show up now. I myself tested with android and chrome.

**Comment by joakim-combain** [comment]
Can you make the store responsive? I'd like to see how our plugins look when the store is responsive. Shouldn't be a problem I guess, but the popup might look weird or something. Don't you think?

**Comment by Boxedsolutions** [comment]
Its theme dependent if the store are Responsive. 

As i have seen in the script for the popup it uses matchMedia to check what size it should bee

**Comment by joakim-combain** [comment]
Ok, so this shouldn't be a problem then. This issue is fixed. Closing it.
