### ISSUE TITLE
Check so that the rounding is implemented correctly

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/opencart#16]

**Comment by Boxedsolutions** [comment]
Normally rounding is handled by a custom rounding module. But I know we need to change our logic for Invoice creation and Vat calculation.

**Comment by andyjohansson** [comment]
Is there some way to get the correct data even though there is a module that´s controlling it?

**Comment by Boxedsolutions** [comment]
Yes Sure, Wee just need to move our tax calculation to the same place where amounts is calculated. 

The rounding is added as a total.

**Comment by andyjohansson** [comment]
Then it should be no trouble accessing it, if the plugins are developed using best practice.

**Comment by Boxedsolutions** [comment]
We had done that implementations on some clients. So i Guess it will not take that much time to do it for the whole module.

**Comment by andyjohansson** [comment]
Super! Then we will sort it out next week.

**Comment by andyjohansson** [comment]
@Boxedsolutions now know what to do.

**Comment by Boxedsolutions** [comment]
it Should be fixed by now, but we need to install a rounding plugin to verify.

**Comment by andyjohansson** [comment]
So you have any example of a rounding plugin?

**Comment by Boxedsolutions** [comment]
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=10016&filter_search=rounding I think this should do it.

**Comment by joakim-combain** [comment]
![checkout](https://cloud.githubusercontent.com/assets/10434920/6040204/6d084246-ac6f-11e4-8482-7c7cbf6f95ba.png)

Seems like it's rounding to nearest 0.5 rather than rounding to nearest whole value.

**Comment by Boxedsolutions** [comment]
Yes its that way. I setup the extension. It did some funny thing when I set to whole currency unit.

You may test to change to different setups in Admin Extensions -> Order totals -> rounding

**Comment by Boxedsolutions** [comment]
I got it, it was needed to be set at multiple to round to whole currency units

**Comment by joakim-combain** [comment]
Looks like it is working correctly now. Closing the issue.
