### ISSUE TITLE
use __construct() instead for method with same name as class

### ISSUE THREAD

**Issue by kalorifri** [Billmate/opencart#167]
Replace
https://github.com/Billmate/opencart/blob/master/billmate/Billmate.php#L32
https://github.com/Billmate/opencart/blob/master/billmate/JSON.php#L133
https://github.com/Billmate/opencart/blob/master/billmate/JSON.php#L783
https://github.com/Billmate/opencart/blob/master/billmate/JSON.php#L797 
with __construct( to prevent the error "PHP Unknown: Methods with the same name as their class will not be constructors in a future version of PHP"

**Comment by Boxedsolutions** [comment]
Good catch. Think none runs php v4 anymore?

**Comment by kalorifri** [comment]
Fixed in release 2.2.2
