### ISSUE TITLE
Version number 2.2.3?

### ISSUE THREAD

**Issue by JoachimTorngren** [Billmate/opencart#177]
Opencart 2.3.0.2 / Billmate 2.2.3

I have installed Billmate 2.2.3 but shows as 2.2.2.2 in backend. Probably forget to change in commonfunctions.php?

**Comment by Boxedsolutions** [comment]
Yes this is a misstake from our side. Will fix to next release..

**Comment by Boxedsolutions** [comment]
Fixed in the next release
