### ISSUE TITLE
Seems like sort order doesn't work.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#19]
I have sort order 1 on Bank, there is no sort order on Part pay. How can Part pay be above Bank then? Also, Invoice has no sort order and is last, Card has sort order 2 and is in third in checkout.

![sort order 1](https://cloud.githubusercontent.com/assets/10434920/6056669/92bbd728-ad14-11e4-8c71-7c7d484d3f44.png)
![sort order 2](https://cloud.githubusercontent.com/assets/10434920/6056670/92bf1078-ad14-11e4-9960-a73f9cfca635.png)
![sort order 3](https://cloud.githubusercontent.com/assets/10434920/6056671/92bf3620-ad14-11e4-8129-d53e0704950d.png)

**Comment by Boxedsolutions** [comment]
Will check this.

**Comment by Boxedsolutions** [comment]
If its no sort_order it comes first. Tried to set it to 4 on partpayment, on opencart154

**Comment by joakim-combain** [comment]
Ok. So is this fixed? Seems like when I checked it was working...

**Comment by andyjohansson** [comment]
This should be fixed then, we open up a new issue if it´s becomes an issue in the future.
