### ISSUE TITLE
I put a card order but no vat was sent in for the products.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#20]
![zero vat](https://cloud.githubusercontent.com/assets/10434920/6057081/30c04fc6-ad1a-11e4-87e1-796f676f160b.png)

**Comment by Boxedsolutions** [comment]
It wasnt setup correct in Backend for the shop. 
The vat classes to use is Moms 25% and Livsmedel. Otherwise Vat become 0.

**Comment by Boxedsolutions** [comment]
But i have changed this articles now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
