### ISSUE TITLE
Country restrictions doesn't work.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#21]
All payment methods are available for norwegian customers. Should only be card available.

![country restrictions 3](https://cloud.githubusercontent.com/assets/10434920/6057449/a1514660-ad1e-11e4-915c-6c42400bc1e2.png)
![country restrictions 1](https://cloud.githubusercontent.com/assets/10434920/6057450/a1545c42-ad1e-11e4-9634-acfc87fcbb64.png)
![country restrictions 2](https://cloud.githubusercontent.com/assets/10434920/6057448/a1512e8c-ad1e-11e4-8703-8be387ff4c36.png)

**Comment by Boxedsolutions** [comment]
The configuration says all zones, I think its the problem

**Comment by Boxedsolutions** [comment]
The shop owner needs to setup Geo Zones for the different payment alternatives. This way it will restrict to the configured countries. 

Maybe we need to add this to the documentation?

**Comment by joakim-combain** [comment]
Can't we restrict them from the plugin? Because if a customer doesn't read the documentation and just allows everyone to use invoice, then if an order from great britain comes in there could be problems I think. @andyjohansson @Boxedsolutions

**Comment by Boxedsolutions** [comment]
You are right in that case. 
One solution would be to create Geo Zones when customer installs the modules and in there have default countries for the payment modules? 

It will then be 4 Geo Zones that will be added. With different countries included? 

then I need to know the countries allowed per module?

Or if we just should make available the different countries and the customer has to uncheck countries that he doesnt want to show or methods in.?

Or if we add hardcoded countries, but in this case when Billmate opens possibilities in a new country customer needs to update their module. 

Whats the best for UserInterface? 
Checkboxes would work I guess?

**Comment by andyjohansson** [comment]
Hmm... How have other gateways resolved this in OpenCart? What´s the Best Practice?

**Comment by joakim-combain** [comment]
My opinion is to hardcode it. It wouldn't be that much of a hassel to update it to a new version. We could just include it when we do other updates.

**Comment by Boxedsolutions** [comment]
Its improved with better UI in backend. 
![country](https://cloud.githubusercontent.com/assets/8977650/6079106/3b790d12-ae01-11e4-98d0-6c6a33f0e0ff.png)

Its autocomplete so just type in some letters. One thing is that opencart database contains countries in English so it will be English country names,

**Comment by andyjohansson** [comment]
Is this implemented for all payment options @Boxedsolutions?
You can test this @joakim-combain if so.

**Comment by Boxedsolutions** [comment]
Yes but i havent configured it with correct countries. But I have tested on 1.5.4 and it seems working.

**Comment by joakim-combain** [comment]
Ok, please configure them and let me know when I can test them, so we aren't working at the same time and something causes confusion. I'll check Prestashop meanwhile.

**Comment by Boxedsolutions** [comment]
All alternatives is allowed in Sweden, Card is set to Allow the countries Denmark, Norway, Sweden

**Comment by joakim-combain** [comment]
Card should be allowed for all countries I think. That's the only one that a customer from say the UK can use. Don't know if @andyjohansson has changed this to only support nordic countries? Also in that case Finland is missing.

**Comment by Boxedsolutions** [comment]
No Its just a misstake by me, but it would be a easy fix.

**Comment by joakim-combain** [comment]
Ok. Which part? :)

**Comment by Boxedsolutions** [comment]
To easy allow All countries for Card.

**Comment by joakim-combain** [comment]
Also, we shouldn't call it "Available countries". Just sounds strange to me...

**Comment by Boxedsolutions** [comment]
What should i call it?

**Comment by joakim-combain** [comment]
Hmm, not sure. That search field maybe it should be called something like Add countries to list and the list be named Activated countries or Allowed countries? @andyjohansson what do you think?

**Comment by joakim-combain** [comment]
Actually maybe "Add allowed countries" and "Allowed countries"?

**Comment by andyjohansson** [comment]
Test again @joakim-combain?

**Comment by joakim-combain** [comment]
Ok, then I'm assuming it should be "Available countries". I don't have time to test right now but I will.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
