### ISSUE TITLE
I set store to english but bank payment window is in swedish still.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#22]
![bank pa engelska 1](https://cloud.githubusercontent.com/assets/10434920/6057536/5e79cb4a-ad1f-11e4-86c3-8df11693792a.png)
![bank pa engelska 2](https://cloud.githubusercontent.com/assets/10434920/6057537/5e956efe-ad1f-11e4-9f61-eed6bb590e79.png)

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
