### ISSUE TITLE
I found this error message still in swedish even though I put store in english.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#23]
Both for invoice and part pay.

![error message](https://cloud.githubusercontent.com/assets/10434920/6057630/36ac3962-ad20-11e4-8cf0-740a58c90595.png)

**Comment by Boxedsolutions** [comment]
This is the response from the Api, I could fix the title and localise that.

**Comment by Boxedsolutions** [comment]
The title also seems to come from the getAddress function

**Comment by andyjohansson** [comment]
This is due to the old API not sending localized translations, closing...
