### ISSUE TITLE
opencart154 store seems to be down, takes forever to load it. Is this just me?

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#24]

**Comment by Boxedsolutions** [comment]
For me its working. It might take some time sometimes. Think its some networking issues with my provider for the VPS its on.

**Comment by joakim-combain** [comment]
Ok, but I have tried reloading and reopening it three times now and won't open it. :/ Maybe it's my browser then...

**Comment by joakim-combain** [comment]
Aha, it worked when I opened in inkognito. So something with my browser. Closing this issue.
