### ISSUE TITLE
When choosing part pay, in store it has decimals but in BO it has rounded the value it seems. They shold be the same. (value per part pay invoice).

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#25]
![part pay 1](https://cloud.githubusercontent.com/assets/10434920/6060186/d190eaa8-ad3a-11e4-859a-e5b51ca99a44.png)
![part pay 2](https://cloud.githubusercontent.com/assets/10434920/6060185/d190319e-ad3a-11e4-8407-012d99f1b04b.png)

**Comment by Boxedsolutions** [comment]
It is now rounded without decimals.

**Comment by joakim-combain** [comment]
this issue is fixed. Closing it.
