### ISSUE TITLE
Says terms of invoice on part pay.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#27]
![terms of invoice](https://cloud.githubusercontent.com/assets/10434920/6060871/3ae8b0ec-ad42-11e4-8af6-48316e057160.png)

**Comment by Boxedsolutions** [comment]
Fixed

**Comment by joakim-combain** [comment]
This needs to be translated as well, should be quick fix.

![translations](https://cloud.githubusercontent.com/assets/10434920/6061126/2f828cde-ad45-11e4-8cfb-2dfca9952ff2.png)

**Comment by Boxedsolutions** [comment]
Should be fixed with latest commit

**Comment by joakim-combain** [comment]
Actually, it looks like the invoice fee should be there instead. Should be the same as in prestashop.

![billmate invoice fee](https://cloud.githubusercontent.com/assets/10434920/6061472/5cb559ae-ad48-11e4-845b-8bf6449794c6.png)

**Comment by Boxedsolutions** [comment]
No its the standard description if you havent set any in the configuration for the module. If you set another text there it will be changed.

**Comment by Boxedsolutions** [comment]
@andyjohansson How do you prefer it would function? Its maybe an enchancement to show the invoice fee with the title, but then we have to redesign this a bit.

**Comment by andyjohansson** [comment]
It should work as in the Prestashop module. Let´s go with the redesign.

**Comment by Boxedsolutions** [comment]
Changed to show invoice fee there.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
