### ISSUE TITLE
Funtion stat in billmate.php needs rewrite

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/opencart#3]
Since most webhosts can't communicate over UDP this only generates errors in the log. The function stat (staring at line 316) needs to be re-writen, both on server and client side.

The current function uses fsockopen on port 51000 over UDP protocol. Most webhosts today block communication through this.

**Comment by andyjohansson** [comment]
This should be deleted.

**Comment by Boxedsolutions** [comment]
There is no stat function with the api-2.0 Billmate file
