### ISSUE TITLE
Test - make sure that the callback is working correctly

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/opencart#30]
Make the same tests and adjustments as we made on the Prestashop module.

**Comment by Boxedsolutions** [comment]
Should be fixed in commit f4387ed2dc63585f1544d1920dfd9965e61343e1 Forgot to reference it.

**Comment by Boxedsolutions** [comment]
it Should work

**Comment by Boxedsolutions** [comment]
closing as it should work
