### ISSUE TITLE
Seems to be an issue with geozones for part pay.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#31]
I get this error message in 156.

Notice: Undefined index: geo_zone_id in /var/www/opencart156.boxedtest.se/public/catalog/model/payment/billmate_partpayment.php on line 21
Notice: Undefined index: geo_zone_id in /var/www/opencart156.boxedtest.se/public/catalog/model/payment/billmate_partpayment.php on line 30

**Comment by Boxedsolutions** [comment]
Yes will fix soon.

**Comment by Boxedsolutions** [comment]
Should be fixed in commit 0dab06b098513919a207f4da621ff0eb126676f7
