### ISSUE TITLE
1.5.6 - I checked out with this person number, 55010110118, and the checkout was unable to load the error message.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#35]
I got this in console:

Failed to load resource: the server responded with a status of 500 (Internal Server Error) 
http://opencart156.boxedtest.se/index.php?route=payment/billmate_invoice/send

**Comment by Boxedsolutions** [comment]
Cant reproduce it. I have tested 3 orders both with coupons and no coupons. Could it be some temporary?

**Comment by joakim-combain** [comment]
Hmm... I managed to get it twice. It's fixed by cleaning out cache. So it's possible that it's just on my side. I did not test this in incognito, so it's very possible that's the issue. I'll try in incognito as well.

**Comment by joakim-combain** [comment]
Confirmed. Seems to be issue with my cache. Closing this issue.
