### ISSUE TITLE
1.5.6 - I created discount code 4444 which is percent and free shipping, we only send free shipping part to BO.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#36]

**Comment by joakim-combain** [comment]
Same error with 5555, it's amount discount and free shipping.

**Comment by Boxedsolutions** [comment]
Hmm, I have to work through that. Try to find some more scenario that make it fails and we will fix it in some way.

**Comment by joakim-combain** [comment]
I think these are the only ones that can be a problem for us. Everything else is handled by opencart. These combo discounts are the only issue I can think of that can be our problem. The rest of the options are just conditions for when the discount is valid. So if there is an issue there then it's opencart issues.

**Comment by Boxedsolutions** [comment]
Is there any possibility to create a discount for a certain product that you have seen? 

I think its necessary to test all possible combos, for us to be sure that we handle discount correct for every situation.

**Comment by joakim-combain** [comment]
Yeah there is. Testing that scenario now.

**Comment by joakim-combain** [comment]
I have tried Percent and fixed amount on specific product and on category as well as free shipping for specific product. All that seems to work great. So only the combo discount is an issue.

**Comment by Boxedsolutions** [comment]
Should be fixed now. I have tested both combos and free_shipping alone and percentage discounts.
