### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/opencart#40]
Implement a way to make sure upgrades get pushed and updated with a button

**Comment by Boxedsolutions** [comment]
Could you explain more?

**Comment by andyjohansson** [comment]
So that we notify the user in the back-end if there is a update available and so that they can update.

**Comment by Boxedsolutions** [comment]
Hmm... Check against releases?

**Comment by andyjohansson** [comment]
Yes, something like it. We maybe could use github for it?
