### ISSUE TITLE
Add support for part payment details on product page

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/opencart#41]

**Comment by Boxedsolutions** [comment]
We need to think about this, for pre 2.0 there is vqMod and after it is ocMod, which is nearly the same. But what if some other modules also mods the same file. It could in worst case crash the product page.

A option to consider is to create a vqmod for the product controller and let the client past in the code that is needed to show the partpayment details.

**Comment by andyjohansson** [comment]
Can't we just have it as an option, enabled / disabled? If it´s disabled it can't crash it?

**Comment by Boxedsolutions** [comment]
dublicate of #34
