### ISSUE TITLE
Tooltip/help is multiple and does not work

### ISSUE THREAD

**Issue by ortax** [Billmate/opencart#43]
Your tooltip / help class does not work and i see double of questionmarks. This is a common misstake when creating an Opencart module. Try instead of using the built in bootstrap data-toggle="tooltip". Separate the help section in language files and call them to your tpl file.

Like so:

In language file: 
$_['tooltip_entry_secret']  = 'Shared secret to use with the Billmate service (provided by Billmate).';

In template file:
<label class="col-sm-2 control-label" for="input-secret"><span data-toggle="tooltip" title="<?php echo $tooltip_entry_secret; ?>"><?php echo $entry_secret; ?></span></label>

In controller file: 
$data['tooltip_entry_secret'] = $this->language->get('tooltip_entry_secret');

**Comment by Boxedsolutions** [comment]
Nice to know. Will fix that as soon as possible.
