### ISSUE TITLE
Undefined index: country_id and name

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#48]
I'm getting following errors in backend Shipping - Invoice.

PHP Notice:  Undefined index: country_id in /xxx/billmate/update.php on line 25
PHP Notice:  Undefined index: name in /xxx/billmate/update.php on line 25

When I'm choosing country (autocomplete) in settings and save it, the invoice method is showing up but when i take a look at settings again and leave without saving anything the country field is being restored and payment method disappear. Errors is coming up regardless.

**Comment by Boxedsolutions** [comment]
Do you have changed the country name from Sweden in the database?

**Comment by kryllem** [comment]
I don't know where is it stored in db but I see now that under System - Localisation - Countries I have it set to Sverige in Country name field.
I have changed it to Sweden now and the errors is gone.

But, why is part payment not affected of that?

**Comment by Boxedsolutions** [comment]
I updated the update file to be compatible with localized country names. To use the iso_code instead.  I will try to work so we can release a new beta as soon as possible. Its nice to get the feedback here so we could fix the issues.

**Comment by Boxedsolutions** [comment]
The cause of this with billmate_invoice was that I had forgot to change the key for our version management for Billmate_invoice. 

OpenCart 2.0 is not allowing to use just version for example I had to change it to billmate_invoice_version to get it persisted to the database
