### ISSUE TITLE
New orders placed under missing orders

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#49]
When order is placed (completed) independed if it is invoice or part payment orders is placed under Missing Orders and not transfered to default dashboard for orders.
When I try to move order to default place (by set a history status to pending (no status was set from the begin)) then I'm getting following errors: Warning: The order could not be found.

When I take a look at db in; oc_order and oc_order_total all fields required seems to be filled.

**Comment by Boxedsolutions** [comment]
Could be because of issue #47

**Comment by kryllem** [comment]
I don't think so. The same issue was in previous version and it's worked.
Another thing is that the title is correct after transaktion is completed.

See attach.
before order is completed
![prt-1](https://cloud.githubusercontent.com/assets/13641326/9133895/a7b1f664-3cff-11e5-8b78-fd5333b89d3a.png)

after order is completed
![prt-2](https://cloud.githubusercontent.com/assets/13641326/9133898/ac50085a-3cff-11e5-971b-9c332e2eb3d0.png)

**Comment by Boxedsolutions** [comment]
The title is caused of #47 the payment titles is now changed to work. 

I did test invoice and partpayment in our test environment and it seems to work.
