### ISSUE TITLE
Total amount rounding not working

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#51]
Total amount rounding doesn't seems to work.

Print Screen from Invoice:
![rounding](https://cloud.githubusercontent.com/assets/13641326/9064689/f3bba854-3acd-11e5-93f9-254ea41a062b.jpg)

**Comment by Boxedsolutions** [comment]
What is the sum in Opencart? Is it another rounding plugin than myoc_price_rounding?

**Comment by kryllem** [comment]
There is no price rounding module at now but I was thinking to implement myoc_price_rounding module.
The sum in OpenCart was 10 848 for the customer view but in counting it was still 10 847,50.I am not using decimal for price (System - Localisation - Currencies - Edit - Decimal Places = Empty field),system seems to round price automatically but only for customer view. 


     Den tisdag, 4 augusti 2015 21:43 skrev Jesper Johansson <notifications@github.com>:
   

 What is the sum in Opencart? Is it another rounding plugin than myoc_price_rounding?—

**Comment by Boxedsolutions** [comment]
ok ok. We should look for the setting for decimal places, sorry to miss that.

But our plugin should be compatible with myoc_price_rounding. 

Do you have access to your database, look up the value for the order total, and you will probably see that opencart rounds the sum in frontend not in the database.

**Comment by kryllem** [comment]
Yes I have access and you have right; the order total is still 10847.5000
I don't know how is it stored in DB but when customers pays with for example skrill; the amount that they are charged is 10848. But I will try with module so there is a place to store round price/value in db.

**Comment by Boxedsolutions** [comment]
The row in for example Billmate invoice is Row 573:
one possibility is if there is another index for example total_text, we could use or just wrap round() around $order_info['total']. It will round the total and rounding will be applied on the invoice. 
                $round = ($order_info['total']*100) - ($orderTotal + $taxTotal);

**Comment by kryllem** [comment]
That sounds as a good option.
I am implementing right now myoc_price_rounding to the store and see how it works.

**Comment by Boxedsolutions** [comment]
I guess this is solved? @kryllem

**Comment by kryllem** [comment]
Yes, solved.
