### ISSUE TITLE
There are some error messages in checkout

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#52]
![opencart-error-message-in-checkout](https://cloud.githubusercontent.com/assets/10434920/9377169/8e7731d4-4716-11e5-8908-71950e6628e1.png)

**Comment by Boxedsolutions** [comment]
This should be fixed

**Comment by joakim-combain** [comment]
If you don't give any available country in partpay, this error message is shown. Perhaps have Sweden set per default for the methods that requires it?

**Comment by Boxedsolutions** [comment]
It sound like a good idea.

**Comment by Boxedsolutions** [comment]
It should bee that way.
