### ISSUE TITLE
I got an error message when trying to checkout with invoice with discount

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#56]
apilogsid: 65765

I used discount code 1111 and 2222 to get this error.

![opencart-error-message-discount](https://cloud.githubusercontent.com/assets/10434920/9378574/d01e92d8-4722-11e5-8933-89f4dac5733d.png)

**Comment by joakim-combain** [comment]
Seems like this issue is for all payment methods.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
