### ISSUE TITLE
Partpay looks terrible in last step of the checkout.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#58]
The radio buttons needs to be moved inside the box and so that it is next to the accurate choice. Also the text field for person number looks malplaced. Not sure where to put it, but put some space between the box and the text for now.

![opencart-design-improvments](https://cloud.githubusercontent.com/assets/10434920/9378769/544bbb02-4724-11e5-903d-641ee2d06072.png)

**Comment by Boxedsolutions** [comment]
Could you check again to see if my design is good

**Comment by joakim-combain** [comment]
Is it possible to shorten the input field to like 1/3 or even 1/4 of the current size and still have it look good? It's too long now I think.

**Comment by Boxedsolutions** [comment]
Yes it is Will do it as soon as possible.

**Comment by Boxedsolutions** [comment]
Should be fixed.

**Comment by joakim-combain** [comment]
I have one small thing left. Try to line up "Billmate delbetalning behöver lite mer information för att processa din order." with "Betalningsalternativ" so that they are aligned.

![opencart equal align](https://cloud.githubusercontent.com/assets/10434920/9487342/ebf99dce-4bd0-11e5-9692-bcd09188af65.png)

**Comment by Boxedsolutions** [comment]
Implemented more aligned styling

**Comment by joakim-combain** [comment]
Looks great! :smile: :+1: Closing this issue.
