### ISSUE TITLE
When selecting partpay and trying to check out I get an error message saying Invalid paymentplanid.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#59]
apilogsid: 65790

![opencart-paymentplanid](https://cloud.githubusercontent.com/assets/10434920/9487370/41d8ea2e-4bd1-11e5-9210-38cc5b8752ba.png)

**Comment by Boxedsolutions** [comment]
it is probably because you use english as language for the site. Will check for a good solution

**Comment by Boxedsolutions** [comment]
Its implemented now.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
