### ISSUE TITLE
Transaction method should be removed in card.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#60]

**Comment by Boxedsolutions** [comment]
I have not heard of this, Bank I know shouldnt have transaction method.

Is it something that has with the future use to do?

**Comment by joakim-combain** [comment]
If you check WooCommerce, it is also missing transaction method in card. As I have understood it, this feature won't be used in the future since it won't be supported. So either it is missing in WooCommerce or it should be removed in opencart. I'm not sure which one it is to be honest.

**Comment by Boxedsolutions** [comment]
Will check this, it might be missing in WooCommerce. I know i have it in Magento on Card but not Bank.

**Comment by Boxedsolutions** [comment]
It should bee there.
