### ISSUE TITLE
We should try to add version number in backend to all payment methods.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#63]

**Comment by Boxedsolutions** [comment]
Its a good idea :+1:

**Comment by Boxedsolutions** [comment]
I have implemented it with adding a - and version number in Billmate payment methods in Admin

**Comment by joakim-combain** [comment]
The title for Bank is misplaced in 1.5.4 and 1.5.6.

![opencart bank text misplaced](https://cloud.githubusercontent.com/assets/10434920/9488096/af5176a6-4bd7-11e5-9754-af8fbf1633e7.png)

**Comment by Boxedsolutions** [comment]
Should be fixed now.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
