### ISSUE TITLE
If I put an order with EUR and use card or bank, the total is wrong in the payment window.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#64]
It shows the unconverted SEK value instead of the converted EUR value.

**Comment by Boxedsolutions** [comment]
Should be implemented

**Comment by joakim-combain** [comment]
It is fixed for card. Waiting to confirm for part pay and invoice.

**Comment by Boxedsolutions** [comment]
Partpay is not supposed to Work with Eur?

**Comment by joakim-combain** [comment]
I'm not sure. I think trustly supports it, not sure if we are going to. I think you will have to check that with Andreas when he comes back.

**Comment by Boxedsolutions** [comment]
Its just to test but I dont think Partpayment support it. 

Bank and invoice its possible to test. I have seen other trustly implementations with euro.

**Comment by joakim-combain** [comment]
Ok, then it should work with different currencies in bank. Part pay is still only SEK. Talk to Andreas when he is back to confirm how he wants it. Rightn ow we have an error message stopping you from using anything else than SEK.

**Comment by Boxedsolutions** [comment]
For now we choose to have only SEK for Bankpayment, the other will be added later on.

**Comment by joakim-combain** [comment]
Ok. In that case this issue is fixed. Closing it.
