### ISSUE TITLE
If the store is set to english, the error messages should be in english.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#66]
There should be a parameter in credentials in our api that changes this.

**Comment by Boxedsolutions** [comment]
I have defined the BILLMATE_LANGUAGE now so we should get localized error messages

**Comment by joakim-combain** [comment]
In 2.0, could we find some way to make these error messages look better? This example is from when putting in 550101101. I also get it when I put 55010110181.

![opencart error message style](https://cloud.githubusercontent.com/assets/10434920/9491519/03fce97a-4bf0-11e5-9a8f-8524c42daf40.png)

**Comment by Boxedsolutions** [comment]
We could fix this with bootstrap css I think

**Comment by Boxedsolutions** [comment]
Should be better looking now

**Comment by joakim-combain** [comment]
The error messages aren't cleaned out when I'm changing the person number.

![opencart_error_message_stacks](https://cloud.githubusercontent.com/assets/10434920/9680148/0ebdd926-52f5-11e5-85cd-732acf3f0281.png)

**Comment by Boxedsolutions** [comment]
Will fix this instantly.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
