### ISSUE TITLE
The values shown in checkout when choosing part pay are wrong.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#67]
The values don't match with the values in the invoice in BO.

See invoice # 8043

I used the following products: iPhone åäö and Sony VAIO 

I chose the 6 months plan.

According to store it should be 302 kr per month but in BO it's 314 kr per month.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
this issue is fixed. Closing it.
