### ISSUE TITLE
Everytime there is something loading, I'm getting a broken icon.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#69]
I'm not sure if this is in our plugin or if it's a store issue.

![opencart broken icon loading](https://cloud.githubusercontent.com/assets/10434920/9488462/8f833d34-4bda-11e5-9a7a-178529fccf9d.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
I'm still getting this issue for bank and card.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
This issue is fixed. Closing this issue.
