### ISSUE TITLE
I've found some texts that needs to be changed

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#70]
These are for invoice and partpay in backend.

"The checkout total the order must reach minimum this payment method becomes active."
Should be 
"The minimum checkout total the order must reach before this payment method becomes active."

"The checkout total the order must reach maximum this payment method becomes active."
Should be
"The maximum checkout total the order must reach before this payment method becomes active."

Perhaps the text needs to be changed further if it's too long.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
There is an " at the end of the part pay text. This is in 1.5.4 and 1.5.6.

**Comment by Boxedsolutions** [comment]
Found it, Should be better now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
