### ISSUE TITLE
Undefined index errors after saving changes in partypayment module

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#71]
I am getting those errors in errorlog after saving changes in Partpayment module

Undefined index: startfee in XXX/system/library/billmate/OpenCartBillmate.php on line 145
Undefined index: handlingfee in XXX/system/library/billmate/OpenCartBillmate.php on line 146
Undefined index: interestrate in XXX/system/library/billmate/OpenCartBillmate.php on line 147
Undefined index: minamount in XXX/system/library/billmate/OpenCartBillmate.php on line 148
Undefined index: maxamount in XXX/system/library/billmate/OpenCartBillmate.php on line 149
Undefined index: startfee in XXX/system/library/billmate/OpenCartBillmate.php on line 145
Undefined index: handlingfee in XXX/system/library/billmate/OpenCartBillmate.php on line 146
Undefined index: interestrate in XXX/system/library/billmate/OpenCartBillmate.php on line 147
Undefined index: minamount in XXX/system/library/billmate/OpenCartBillmate.php on line 148
Undefined index: maxamount in XXX/system/library/billmate/OpenCartBillmate.php on line 149

**Comment by Boxedsolutions** [comment]
Ahh a logic issue, Will fix instantly

**Comment by Boxedsolutions** [comment]
Should be fixed now
