### ISSUE TITLE
Round amount two times on invoice

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#74]
Rounding amount is at two places on invoice.

![rounding-invoice](https://cloud.githubusercontent.com/assets/13641326/9601954/0e477d5a-50a5-11e5-81f6-2a369d8edab6.png)

**Comment by Boxedsolutions** [comment]
Do you use the Myoc Rounding plugin?

**Comment by kryllem** [comment]
Yes, I am.

**Comment by Boxedsolutions** [comment]
Ok, We should see if we could merge this two rounding totals in someway.

**Comment by Boxedsolutions** [comment]
Should be fixed
