### ISSUE TITLE
Notify website owner when order unsuccessful due to credit check

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#75]
It would be good to have some place to see which orders wasn't completed due to credit check.
Stor owner should get a message from the beginning about it but it doesn't seems to work.

**Comment by Boxedsolutions** [comment]
Please Clarify, 

How should this information be presented in OpenCart? A not Completed order should be placed under Missing order.

**Comment by kryllem** [comment]
Missing order doesn't show the reason why order wasn't completed.

Information could be presented for example under Reports - Sales - Billmate
Or
Simply by sending an email to store e-mail about it.
