### ISSUE TITLE
GetAddress plugin compatibility with Quick Checkout modules

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#76]
Many store owners uses some of Quick Checkout modules to make it easy for shoppers to get through checkout.
It would be nice to have getAddress feature compatible with some of them.
For example with AJAX Quick Checkout developed by Dreamvention.
Or make getAdress module be able to assign it to checkout layout.

**Comment by Boxedsolutions** [comment]
I now there is many Checkout types for Opencart, but its fully possible to modify our billmate_getaddress.ocmod.xml to fit other checkouts. 

Its just to check the appropriate template file and se where it should be input and add a section to our mod.

**Comment by kryllem** [comment]
When it comes to Ajax Quick Checkout in my case it's not so easy.


>"Artem (Dreamvention)
>Sep 8, 18:12
>
>in order to add the field is not enough to simply add the code that you have sent in a file tpl.
>
>Best regards, Artem
>Support Department
>The Dreamvention team"

**Comment by Boxedsolutions** [comment]
Will look at quick checkout later, In the old Oc 1.5 it was no problem.

**Comment by kryllem** [comment]
That would be nice, i have spent whole day to figure it out but without any progress.

**Comment by kryllem** [comment]
Refresh.

**Comment by Boxedsolutions** [comment]
We have tried to talk to Dreamvention about it and their lack of support is a problem when we are try to make a fix for this as we do not want to modify any of their core files. 

Its maybe possible that they add it if more people ask them.
