### ISSUE TITLE
Values differ in checkout and in payment window when using EUR.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#77]
I changed to EUR as currency and chose to use card. When I get to payment window we show decimals, which was not shown in the checkout. We should always show the same amount in payment window as in checkout.

I used: Sony VAIO, iPhone åäö, åäö as discount code and per item shipping rate.

**Comment by andyjohansson** [comment]
What is the status on this one @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Cant reproduce it.
