### ISSUE TITLE
Values differ from store to BO when using EUR. The value in store is higher than in BO.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#78]
See invoice # 8114 and order # 143.

**Comment by Boxedsolutions** [comment]
Think it is solved now. its now a rule to use the higher of the rounding values, MyOc vs Billmate

**Comment by joakim-combain** [comment]
There is one small issue. In our pdf it now says one öre too much. See invoice # 8120.

**Comment by Boxedsolutions** [comment]
I shall see if I could solve it in some way. But why is it rounded in one way in the overview and one way on the pdf?

**Comment by joakim-combain** [comment]
I have no idea, really. Our developer is away on lunch so I can't ask him at the moment.

**Comment by joakim-combain** [comment]
He just came in, will check with him.

**Comment by Boxedsolutions** [comment]
I Checked the log and the value for the total is 60,002986689684 Euro so it seems odd to round up to 60,01?
