### ISSUE TITLE
CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead

### ISSUE THREAD

**Issue by JoachimTorngren** [Billmate/opencart#81]
I'm not a coder so I'm not entirely sure if this error is due to the Billmate code or my host setup.

Billmate v2.0
Opencart v2.0.3.1

During installation of Billmate Bank, Card and Invoice I received the following errors:

curl_setopt() [<a href='function.curl-setopt'>function.curl-setopt</a>]: CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in xxx/billmate/Billmate.php on line 102

Cannot modify header information - headers already sent by (output started at xxx/admin/index.php:84) in xxx/system/library/response.php on line 12

**Comment by Boxedsolutions** [comment]
Open billmate/Billmate.php and change this line around 103:
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, $vh);
to
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);

And it should work

Its a issue that have with installed php version, we will find a solution for this soon. But

**Comment by JoachimTorngren** [comment]
Changed both 
billmate/Billmate.php 
AND 
system/library/billmate/Billmate.php
to make error go away.

**Comment by andyjohansson** [comment]
Since 2.0.1 is released, should I push this to 2.1 for next week @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Fixed with the new 2.1 release
