### ISSUE TITLE
Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by JoachimTorngren** [Billmate/opencart#82]
When using Billmate Bank or Card I get the following error after redirection from Billmate payment window:

00Warning: Cannot modify header information - headers already sent by (output started at xxx/billmate/Billmate.php:84) in xxx/system/library/response.php on line 12

Billmate v2.0
Opencart v2.0.3.1

**Comment by andyjohansson** [comment]
Hi and thanks for reporting this @JoachimTorngren. We will look into it ASAP.
Could you take a look @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Could you open /billmate/Billmate.php and add // before line 84 and line 86? It should solve this issue.

**Comment by andyjohansson** [comment]
Is this in the new release?

**Comment by Boxedsolutions** [comment]
There is a new Release that fix this.
I have not found this in the tests we have done earlier.
