### ISSUE TITLE
Text title contains images

### ISSUE THREAD

**Issue by JoachimTorngren** [Billmate/opencart#93]
catalog/language/swedish/payment/billmate_bankpay.php
and 
catalog/language/swedish/payment/billmate_cardpay.php

row 4 ($_['text_title']) contains image and links instead of text only. 

This causes problems with 3-rd party quick checkouts (in this case Ajax Quick Checkout by Dreamvention) where the text and image is incorrecty displayed in frontend. Suggestment to stick to text only as intended.

![image](https://cloud.githubusercontent.com/assets/14246807/10390781/19f9314a-6e7b-11e5-94d0-9b9800fb77ad.png)

Billmate 2.1.1
Opencart 2.0.3.1

**Comment by Boxedsolutions** [comment]
Will check this, it did work with quick checkout before 2.0.

**Comment by JoachimTorngren** [comment]
Yes - correct. No problem on opencart 1.5.6 and same quick checkout.

**Comment by Boxedsolutions** [comment]
Have you tried our latest release if this resolves the problem.
