### ISSUE TITLE
Store owner email missing from Billmate online

### ISSUE THREAD

**Issue by JoachimTorngren** [Billmate/opencart#94]
I'm not recieving any emails (NOTIFIERING: En ny faktura är skapad (Billmate): [customer name] from BIllmate online for Billmate module 2.1.1.

I have an older version of Billmate for Opencart 1.5.6 where it works fine.

Billmate 2.1.1
Opencart 2.0.3.1

**Comment by Boxedsolutions** [comment]
Please add send us a mail at support@billmate.se swedish language is accepted

**Comment by JoachimTorngren** [comment]
Issue will be solved in Billmate Online
