### ISSUE TITLE
Incorrect order number in Billmate payment window

### ISSUE THREAD

**Issue by JoachimTorngren** [Billmate/opencart#96]
Billmate order window displays different order number than store order number. Might be confusing for customers.

In this case displayed order number is 2523. Store order number is 201560348.

![image](https://cloud.githubusercontent.com/assets/14246807/10391234/f3c4c7d4-6e7d-11e5-9e39-3cbd885b139b.png)

Billmate 2.1.1
Opencart 2.0.3.1

**Comment by Boxedsolutions** [comment]
@andyjohansson Could you check if this is solvable

**Comment by andyjohansson** [comment]
Hi @Boxedsolutions, can you define what is solvable? The info that is sent from the store goes into the view. The question is where 2523 comes from. It´s like this in the teststore as well.
I think the thing is that the order ID is not set in OpenCart before the payment is settled. Therefor we send the cart id instead, just like in PrestaShop? Am I correct @Boxedsolutions.

**Comment by Boxedsolutions** [comment]
Hi @andyjohansson This number comes not from Opencart, and is not cart id. 
<img width="2067" alt="skarmavbild 2015-10-12 kl 09 01 36" src="https://cloud.githubusercontent.com/assets/8977650/10422851/59a07398-70c0-11e5-83ab-7addde9711bb.png">

**Comment by JoachimTorngren** [comment]
Issue will be solved in Billmate Online.

**Comment by JoachimTorngren** [comment]
Sorry was not closed..

**Comment by Boxedsolutions** [comment]
@kalorifri Can you check if the ordernumber from store matches this order id in case it does. Close the issue

**Comment by kalorifri** [comment]
Cant recreate issue, it seems to be fixed and closing this ticket
