### ISSUE TITLE
Improved layout with radiobuttons

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/opencart#97]
<img width="1189" alt="skarmavbild 2015-10-10 kl 13 34 41" src="https://cloud.githubusercontent.com/assets/4968755/10410956/ba75a936-6f53-11e5-97d2-b5db141684ce.png">

**Comment by Aviree** [comment]
This has been fixed, see attached picture
![opencheckout](https://cloud.githubusercontent.com/assets/14887835/12353818/fb132632-bb91-11e5-9918-ab4e5dc1e4d5.png)
