### ISSUE TITLE
We have a setting called Status saying Yes and No and is a drop down list.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#99]
This setting should probably be Activated: Yes/No but I'm not sure.

![opencart-bank-backend-status](https://cloud.githubusercontent.com/assets/10434920/10578415/53433ce4-7672-11e5-9120-fecda95dbbf1.png)

**Comment by joakim-combain** [comment]
Can we get this fixed soon? I'm updating the manuals and can't do the opencart one until this is fixed.

**Comment by Boxedsolutions** [comment]
We fix it as soon as we have time. Great that you are doing the manuals :)

**Comment by joakim-combain** [comment]
Ok. Yeah, magento, prestashop, oscommerce and Woocommerce are done, but not uploaded. It's nice to have them updated. :smile:

**Comment by Boxedsolutions** [comment]
Yes it saves some support time also :) Will try to fix this before lunch.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
I noticed that in invoice and part pay, Activated is not on top like in card and bank. Is this planned or should it be on top in there as well? I just feel like it's weird to not have the same structure in the plugins.

**Comment by Boxedsolutions** [comment]
It should now be on the top, I think you`re right about the structure.

**Comment by joakim-combain** [comment]
Ok. I'll check and compare the plugins and see if there are more things that needs to be adjusted, but I'll create a new task about that if there is anything that needs to be changed. Closing this issue.
